### ISSUE TITLE
I can not download the data of Link Sets.

### ISSUE THREAD

**Issue by beibeixiaomu** [CyTargetLinker/cytargetlinker#25]
Hi,
   I'm sorry that I can not open the URLs of Link Sets. I can not download mirtarbase_hsa_7.0.xgmml.zip and other data. (https://projects.bigcat.unimaas.nl/data/cytargetlinker/linksets/mirtarbase/mirtarbase_hsa_7.0.xgmml.zip) I can not open it.
Could you help me to check it? Thank you very much.
Best wishes

**Comment by besli** [comment]
I am the same problem on it. Anyone can help me out?

**Comment by mkutmon** [comment]
Sorry, we had a cyberattack at the university and our servers are still down. We are trying hard to get them back online. Nevertheless, I will move them somewhere else now and update the links. I am sorry about the inconvenience.

**Comment by mkutmon** [comment]
miRTarBase should now be downloadable again. I will try to provide as many of the other collections too.

**Comment by mingxu-cy** [comment]
Can not download the microRNA-target gene linksetshttps://projects.bigcat.unimaas.nl/cytargetlinker/linksets/

**Comment by mkutmon** [comment]
Hi, please use the new website for downloads:
https://cytargetlinker.github.io/pages/linksets

**Comment by beibeixiaomu** [comment]
Ok, thank you very much~





------------------ Original ------------------
