### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by fehrhart** [CyTargetLinker/cytargetlinker#30]
When trying to download mirtarbase_hsa_8.0.xgmml.zip from https://cytargetlinker.github.io/pages/linksets/mirtarbase I get the following error.
Same for mirtarbase_mmu_8.0.xgmml.zip
The other one works.

![image](https://user-images.githubusercontent.com/11389574/83020531-e20f2200-a028-11ea-8b80-0fd7273127e3.png)

Windows 10, firefox
Chris had the same problem with Mac

**Comment by mkutmon** [comment]
strange. should work now.

**Comment by fehrhart** [comment]
Same error for trying download WP/Reactome linksets today (tried both firefox and chrome)

![image](https://user-images.githubusercontent.com/11389574/124375224-6bb80700-dca1-11eb-8350-b30a663602cd.png)
