### ISSUE TITLE
Issue with linksets in WikiPathways

### ISSUE THREAD

**Issue by aish181095** [CyTargetLinker/cytargetlinker#34]
There seems to be a problem while downloading the WikiPathways linksets for release 2021-01-10 version. I get an error 404 while trying to save the link. 

Thank you for the help.

**Comment by mkutmon** [comment]
thanks, I will have a look what is going on.

**Comment by mkutmon** [comment]
should be solved. let me know if you still run into issues.

**Comment by ashviyer** [comment]
I stil get the error when trying to save the link (wikipathways-hsa-curated-20210110.xgmml):

{"message":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.","status":404}

**Comment by mkutmon** [comment]
sorry it was a permission issue. it is solved now.
